version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:12

commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: npm install
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: unit test
          #          command: npm test
          command: jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: test-reports
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
