version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12
commands:
  restore_modules:
    steps:
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  save_modules:
    steps:
      - save_cache:
          key:  dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: npm install
      - save_modules
  test:
    executor: node
    steps:
      - checkout
      - restore_modules
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: unit test
          command: npm ci

          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/junit/
      - store_test_results:
          path: reports/junit/
      - store_artifacts:
          path: reports/junit/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test











#version: 2.1
#orbs:
#  node: circleci/node@1.1.6
#jobs:
#  build-and-test:
#    executor:
#      name: node/default
#    steps:
#      - checkout
#      - node/with-cache:
#          steps:
#            - run: npm install
#            - run: npm ci
#            - environment:
#                JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
#
#      - store_test_results:
#          path: reports/junit
#      - store_artifacts:
#          path: reports/junit
#
#
#workflows:
#  build-and-test:
#    jobs:
#      - build-and-test






