version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/node:12

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-dependencies-{{ .Branch }}

      - run:
          name: install dependencies
          command: |
            npm install
            npm install jest

      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}


      - run:
          name: run tests
          command: |
            jest
          #            jest  --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"

#      - store_test_results:
#          path: test-reports









